CREATE DATABASE  IF NOT EXISTS `db`;
USE `db`;
create table hotels
(
    hotelID     int auto_increment
        primary key,
    name        varchar(100)  not null,
    city        varchar(50)   not null,
    address     varchar(100)  null,
    description text          not null,
    rating      decimal(4, 1) null,
    imageURL    varchar(300)  null
);

INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (1, 'Hyatt Regency Monterey Hotel & Spa', 'Monterey', '1 Old Golf Course Rd, Monterey CA 93940 USA', 'Book HyettRegency Monterey For Instant Savings! - Book Now. Great Rates in Seconds. Real Guest Reviews. 24/7 Customer Service. Check savings and offers. Deals up to 50% off. Amenities: Secure Incredible Value, Expert Advice & Support, Book Online or Call.', 4.0, 'https://exp.cdn-hotels.com/hotels/1000000/20000/18200/18152/b12c5aaa_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (2, 'The Monterey Hotel', 'Monterey', '407 Calle Principal, Monterey CA 93940 USA', 'The Monterey Hotel. Price Guarantee. Browse Reviews & Photos. Our Customer Service Team is on Hand Day and Night to Personally Guide You. Save with Secret Prices. Family-Friendly Hotels. Flexible Payment Options. Last Minute Hotel Deals. Deals of the Day.', 4.0, 'https://exp.cdn-hotels.com/hotels/1000000/20000/12400/12377/d1fdaaee_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (3, 'Casa Munras Garden Hotel & Spa', 'Monterey', '700 Munras Ave, Monterey CA 93940 USA', 'Currently Remains Open & Committed to a Safe Hospitality Experience in a Nature! Centrally Located In Historic Downtown Monterey, Minutes From World-Renowned Attractions. Pet-Friendly Hotel. Family Friendly Hotel. Commitment to Your Safety. We are Open.', 3.8, 'https://exp.cdn-hotels.com/hotels/1000000/40000/35900/35893/9e85d352_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (4, 'Omni San Diego Hotel', 'San Diego', '675 L St, San Diego CA 92101 USA', 'Located in the heart of the historic Gaslamp Quarter and across from the convention center, our hotel puts you close to the city''s most popular tourist attractions.', 4.5, 'https://exp.cdn-hotels.com/hotels/1000000/990000/982500/982408/b3023fcb_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (5, 'Westgate Hotel', 'San Diego', '1055 Second Ave, San Diego CA 92101 USA', 'Save up to 55% on your Attraction Tickets, Shuttle Transportation and More. Find the Lowest Villa Packages when you Book with Westgate Reservations. Package deals. Best price guarantee. Expert friendly advice. Pet friendly. Make your reservation.', 4.8, 'https://exp.cdn-hotels.com/hotels/1000000/30000/24600/24548/cda2e716_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (6, 'Rancho Bernardo Inn San Diego', 'San Diego', '17550 Bernardo Oaks Dr, San Diego CA 92128 USA', 'Summer Call for an Escape to Rancho Bernardo to Recharge - Your 4th Night Is on Us & More! Drive Into San Diego This Summer for a Perfect Getaway. Free Parking & Daily Credit! Gift Cards Available. Take A Tour. Book Online. Amenities: Swimming Pool, Spa, Restaurant.', 4.3, 'https://exp.cdn-hotels.com/hotels/1000000/10000/3100/3007/76a62f4d_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (7, 'Gaia Hawaii at Trump Waikiki Hotel', 'Honolulu', '223 Saratoga Road, Honolulu HI 96815 USA', 'Gaia Hawaii at Trump Waikiki Hotel. Gaia Hawaii at Trump Waikiki Hotel offers 7 air-conditioned accommodations with irons/ironing boards and complimentary toiletries. Flat-screen televisions are featured in guestrooms. Guests can surf the web using the complimentary wireless Internet access.', 4.9, 'https://exp.cdn-hotels.com/hotels/20000000/19250000/19240400/19240301/e4eb4ece_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (8, 'Lotus Honolulu at Diamond Head', 'Honolulu', '2885 Kalakaua Ave, Honolulu HI 96815 USA', 'Opposite Kapiolani Park, this polished hotel with views of the Pacific Ocean and Diamond Head volcanic peak is 3 miles from Ala Moana, a shopping mall, and 4 miles from the Honolulu Museum of Art. 
Stylish, airy rooms offer WiFi, iPod docks, flat-screens, coffeemakers and private lanais. Most add ocean views. A penthouse suite features 2 bedrooms, a kitchen and a wraparound terrace.', 4.2, 'https://exp.cdn-hotels.com/hotels/1000000/70000/63200/63177/12bef01d_z.jpg?impolicy=fcrop&w=773&h=530&q=high');
INSERT INTO db.hotels (hotelID, name, city, address, description, rating, imageURL) VALUES (9, 'Outrigger Waikiki Beach Resort', 'Honolulu', '2335 Kalakaua Ave, Honolulu HI 96815 USA', 'Set on Waikiki Beach, this upscale oceanfront resort is 0.8 miles from the Honolulu Zoo, 1 mile from the Waikiki Aquarium and 1.9 miles from Ala Moana Beach Park.
The understated rooms include tropical wood furniture, coffeemakers and free Wi-Fi; some have balconies with ocean views. Suites add panoramic ocean vistas, whirlpool tubs and pull-out sofas.', 4.6, 'https://exp.cdn-hotels.com/hotels/1000000/20000/13800/13791/284f3af6_z.jpg?impolicy=fcrop&w=773&h=530&q=high');